### ISSUE TITLE
Add coordinates options

### ISSUE THREAD

**Issue by Thompie2000** [snhobbs/kicad-testpoints-pcm#3]
Hello

I use your plugin and it's works fine. But the problem is that i prefer more the X-axis increases right and Y-axis increases up. The Y-axis don't work for me. It will take always Y-axis increases down. The other issue is when i change the drill/place origin. the plugin don't look the newest coordination of the drill/place origin, but it will always look at the dx and dy coordination.

Can you maybe fix this issue?

thank you for this plugin

**Comment by snhobbs** [comment]
Thanks for your input! Looks like that's perfectly doable. Look for it in the next version!

**Comment by snhobbs** [comment]
Okay v0.1.8 switches to Cartesian coordinates and has the option to use an aux origin. 

Test PCM repository: https://gitlab.com/snhobbs/metadata/-/jobs/7135491689/artifacts/raw/artifacts/repository.json
